### ISSUE TITLE
STB-Diffchecker 実行時エラーについて

### ISSUE THREAD

**Issue by tsumiyama** [NS-NS/STB-DiffChecker#2]
@Y-Sakai 
ファイルA、ファイルBに対するエラーを処理した後、実行を選択しても、ツール自体が落ちてしまう現象が発生します。
これも、ST-Bridgeのフォーマットに相違があることにより起きる事象でしょうか。

**Comment by Y-Sakai** [comment]
@tsumiyama 
いただいた情報ではツール側に問題があるのかST-Bridgeファイル側に問題あるのかが判断つきませんでした。
共有していただけるのであれば、二つのST-Bridgeファイルを添付いただけますか。

**Comment by tsumiyama** [comment]
@Y-Sakai 
ST-Bridgeファイルを添付させていただきます。
テストとして、ファイルA・B両方に[B_File_Revit2020]を入れてみたところ、
実行ができたので、[A_file_SS]に対しての何か問題があるのかと思うのですが、
それ以上の判断ができませんでした。
[210702_Github_STB.zip](https://github.com/NS-NS/STB-DiffChecker/files/6751581/210702_Github_STB.zip)

**Comment by Y-Sakai** [comment]
@tsumiyama 
いくつかプログラムの不具合があったので修正しました。

**Comment by tsumiyama** [comment]
@Y-Sakai 
修正後のプログラムでは実行できました。
対応ありがとうございます。
